Select  'LOCN' As Table_Name,
        Row_number() Over (Order By LTrim(RTrim(Replace(locn.loc_code, Chr(160), ' ')))) As RowNumber,
        LTrim(RTrim(Replace(locn.loc_code, Chr(160), ' '))) AS loc_code, 
        LTrim(RTrim(Replace(locn.descr, Chr(160), ' '))) AS descr, 
        LTrim(RTrim(Replace(locn.short_descr, Chr(160), ' '))) AS short_descr, 
        LTrim(RTrim(Replace(locn.addr_line_1, Chr(160), ' '))) AS addr_line_1, 
        LTrim(RTrim(Replace(locn.addr_line_2, Chr(160), ' '))) AS addr_line_2, 
        LTrim(RTrim(Replace(locn.addr_city, Chr(160), ' '))) AS addr_city, 
        LTrim(RTrim(Replace(locn.addr_state, Chr(160), ' '))) AS addr_state, 
        LTrim(RTrim(Replace(locn.addr_cntry, Chr(160), ' '))) AS addr_cntry, 
        LTrim(RTrim(Replace(locn.addr_postcd, Chr(160), ' '))) AS addr_postcd, 
        LTrim(RTrim(Replace(locn.phone_num_1, Chr(160), ' '))) AS phone_num_1, 
        LTrim(RTrim(Replace(locn.phone_num_2, Chr(160), ' '))) AS phone_num_2, 
        LTrim(RTrim(Replace(locn.comp_code, Chr(160), ' '))) AS comp_code, 
        locn.update_date AS update_date 
From locn locn 
Order By LTrim(RTrim(Replace(locn.loc_code, Chr(160), ' ')))

Select  'IMST' As Table_Name,
        Row_number() Over (Order By LTrim(RTrim(Replace(imst.item_code, Chr(160), ' ')))) As RowNumber,
        LTrim(RTrim(Replace(imst.item_code, Chr(160), ' '))) AS item_code, 
        LTrim(RTrim(Replace(imst.descr, Chr(160), ' '))) AS descr, 
        LTrim(RTrim(Replace(imst.short_descr, Chr(160), ' '))) AS short_descr, 
        LTrim(RTrim(Replace(imst.usage_code, Chr(160), ' '))) AS usage_code, 
        LTrim(RTrim(Replace(imst.item_cat, Chr(160), ' '))) AS item_cat, 
        LTrim(RTrim(Replace(imst.matl_type, Chr(160), ' '))) AS matl_type, 
        LTrim(RTrim(Replace(imst.invy_item_code, Chr(160), ' '))) AS invy_item_code, 
        LTrim(RTrim(Replace(imst.order_uom, Chr(160), ' '))) AS order_uom, 
        LTrim(RTrim(Replace(imst.price_uom, Chr(160), ' '))) AS price_uom, 
        LTrim(RTrim(Replace(imst.invy_uom, Chr(160), ' '))) AS invy_uom, 
        LTrim(RTrim(Replace(imst.purch_uom, Chr(160), ' '))) AS purch_uom, 
        LTrim(RTrim(Replace(imst.batch_uom, Chr(160), ' '))) AS batch_uom, 
        LTrim(RTrim(Replace(imst.rpt_uom, Chr(160), ' '))) AS rpt_uom, 
        LTrim(RTrim(Replace(imst.agg_size, Chr(160), ' '))) AS agg_size, 
        LTrim(RTrim(Replace(imst.cem_type, Chr(160), ' '))) AS cem_type, 
        imst.days_to_strgth AS days_to_strgth, 
        imst.max_water AS max_water, 
        imst.water_cem_ratio AS water_cem_ratio, 
        imst.pct_air AS pct_air, 
        LTrim(RTrim(Replace(imst.slump, Chr(160), ' '))) AS slump, 
        LTrim(RTrim(Replace(imst.slump_uom, Chr(160), ' '))) AS slump_uom, 
        imst.strgth AS strgth, 
        LTrim(RTrim(Replace(imst.strgth_uom, Chr(160), ' '))) AS strgth_uom, 
        imst.water_hold AS water_hold, 
        LTrim(RTrim(Replace(imst.cust_code, Chr(160), ' '))) AS cust_code, 
        LTrim(RTrim(Replace(imst.proj_code, Chr(160), ' '))) AS proj_code, 
        imst.min_temp AS min_temp, 
        LTrim(RTrim(Replace(imst.min_temp_uom, Chr(160), ' '))) AS min_temp_uom, 
        imst.pct_recycle AS pct_recycle, 
        LTrim(RTrim(Replace(imst.order_qty_ext_code, Chr(160), ' '))) AS order_qty_ext_code, 
        imst.order_dosage_qty AS order_dosage_qty, 
        LTrim(RTrim(Replace(imst.order_dosage_qty_uom, Chr(160), ' '))) AS order_dosage_qty_uom, 
        LTrim(RTrim(Replace(imst.price_qty_ext_code, Chr(160), ' '))) AS price_qty_ext_code, 
        LTrim(RTrim(Replace(imst.tkt_qty_ext_code, Chr(160), ' '))) AS tkt_qty_ext_code, 
        LTrim(RTrim(Replace(imst.delv_uom, Chr(160), ' '))) AS delv_uom, 
        imst.per_cem_wgt_divisor AS per_cem_wgt_divisor, 
        imst.lwt_qty AS lwt_qty, 
        LTrim(RTrim(Replace(imst.lwt_qty_uom, Chr(160), ' '))) AS lwt_qty_uom, 
        imst.min_cem_cont AS min_cem_cont, 
        imst.air_pct AS air_pct, 
        imst.content_price AS content_price, 
        imst.content_up_price AS content_up_price, 
        imst.content_down_price AS content_down_price, 
        LTrim(RTrim(Replace(imst.batch_code, Chr(160), ' '))) AS batch_code, 
        imst.pct_asphalt_recycle AS pct_asphalt_recycle, 
        imst.asphaltic_cem_qty AS asphaltic_cem_qty, 
        LTrim(RTrim(Replace(imst.asphaltic_cem_qty_uom, Chr(160), ' '))) AS asphaltic_cem_qty_uom, 
        imst.oil_qty AS oil_qty, 
        LTrim(RTrim(Replace(imst.oil_qty_uom, Chr(160), ' '))) AS oil_qty_uom, 
        imst.load_var_pct AS load_var_pct, 
        imst.modified_date AS modified_date, 
        imst.min_cem_override_flag AS min_cem_override_flag, 
        imst.const_substitution_flag AS const_substitution_flag, 
        imst.include_in_yield_flag AS include_in_yield_flag, 
        LTrim(RTrim(Replace(imst.dose_uom, Chr(160), ' '))) AS dose_uom, 
        imst.dose_extension_code AS dose_extension_code, 
        imst.dose_divisor AS dose_divisor, 
        imst.dose_dosage_qty AS dose_dosage_qty, 
        LTrim(RTrim(Replace(imst.dose_delv_uom, Chr(160), ' '))) AS dose_delv_uom, 
        LTrim(RTrim(Replace(imst.sort_code, Chr(160), ' '))) AS sort_code, 
        LTrim(RTrim(Replace(imst.max_slump, Chr(160), ' '))) AS max_slump, 
        LTrim(RTrim(Replace(imst.min_slump, Chr(160), ' '))) AS min_slump, 
        LTrim(RTrim(Replace(imst.modifier_slump, Chr(160), ' '))) AS modifier_slump, 
        LTrim(RTrim(Replace(imst.max_water_uom, Chr(160), ' '))) AS max_water_uom, 
        LTrim(RTrim(Replace(imst.item_status_code, Chr(160), ' '))) AS item_status_code, 
        imst.modify_admix_flag AS modify_admix_flag, 
        imst.max_age_of_concrete AS max_age_of_concrete, 
        imst.min_load_size AS min_load_size, 
        LTrim(RTrim(Replace(imst.include_in_sampling_code, Chr(160), ' '))) AS include_in_sampling_code, 
        imst.sampling_interval AS sampling_interval, 
        LTrim(RTrim(Replace(imst.sampling_interval_uom, Chr(160), ' '))) AS sampling_interval_uom, 
        LTrim(RTrim(Replace(imst.truck_type, Chr(160), ' '))) AS truck_type, 
        imst.max_load_size AS max_load_size, 
        LTrim(RTrim(Replace(imst.strgth2_code, Chr(160), ' '))) AS strgth2_code, 
        imst.time_to_strgth2 AS time_to_strgth2, 
        LTrim(RTrim(Replace(imst.time_to_strgth2_uom, Chr(160), ' '))) AS time_to_strgth2_uom, 
        LTrim(RTrim(Replace(imst.strgth3_code, Chr(160), ' '))) AS strgth3_code, 
        imst.time_to_strgth3 AS time_to_strgth3, 
        LTrim(RTrim(Replace(imst.time_to_strgth3_uom, Chr(160), ' '))) AS time_to_strgth3_uom, 
        imst.job_washdown_time AS job_washdown_time, 
        LTrim(RTrim(Replace(imst.inactive_code, Chr(160), ' '))) AS inactive_code, 
        imst.inactive_date AS inactive_date, 
        imst.max_temp AS max_temp, 
        LTrim(RTrim(Replace(imst.slump_type, Chr(160), ' '))) AS slump_type, 
        LTrim(RTrim(Replace(imst.legacy_item_code, Chr(160), ' '))) AS legacy_item_code, 
        imst.dosage_slump_increase AS dosage_slump_increase, 
        imst.update_date AS update_date 
From imst imst 
Order By LTrim(RTrim(Replace(imst.item_code, Chr(160), ' ')))

Select  'ILOC' As Table_Name,
        Row_number() Over (Order By LTrim(RTrim(Replace(iloc.loc_code, Chr(160), ' '))), LTrim(RTrim(Replace(iloc.item_code, Chr(160), ' ')))) As RowNumber,
        LTrim(RTrim(Replace(iloc.item_code, Chr(160), ' '))) AS item_code, 
        LTrim(RTrim(Replace(iloc.loc_code, Chr(160), ' '))) AS loc_code, 
        iloc.curr_std_cost AS curr_std_cost, 
        iloc.prev_std_cost AS prev_std_cost, 
        LTrim(RTrim(Replace(iloc.cost_ext_code, Chr(160), ' '))) AS cost_ext_code, 
        LTrim(RTrim(Replace(iloc.prev_cost_ext_code, Chr(160), ' '))) AS prev_cost_ext_code, 
        iloc.mixer_time AS mixer_time, 
        iloc.moist_pct AS moist_pct, 
        iloc.spec_grav AS spec_grav, 
        LTrim(RTrim(Replace(iloc.batch_uom, Chr(160), ' '))) AS batch_uom, 
        LTrim(RTrim(Replace(iloc.batch_code, Chr(160), ' '))) AS batch_code, 
        iloc.batch_mix_dwnld_flag AS batch_mix_dwnld_flag, 
        iloc.max_batch_size AS max_batch_size, 
        iloc.max_qty AS max_qty, 
        iloc.min_qty AS min_qty, 
        iloc.reord_qty AS reord_qty, 
        iloc.lead_time AS lead_time, 
        iloc.std_cost_effect_date AS std_cost_effect_date, 
        iloc.last_date_used AS last_date_used, 
        iloc.last_date_ordered AS last_date_ordered, 
        LTrim(RTrim(Replace(iloc.stor_loc_code, Chr(160), ' '))) AS stor_loc_code, 
        LTrim(RTrim(Replace(iloc.matl_type, Chr(160), ' '))) AS matl_type, 
        iloc.yield AS yield, 
        LTrim(RTrim(Replace(iloc.yield_uom, Chr(160), ' '))) AS yield_uom, 
        iloc.water_cem_ratio AS water_cem_ratio, 
        iloc.disc_amt AS disc_amt, 
        LTrim(RTrim(Replace(iloc.disc_amt_uom, Chr(160), ' '))) AS disc_amt_uom, 
        iloc.cem_content AS cem_content, 
        iloc.cemnt_content AS cemnt_content, 
        iloc.contri_pct_to_cem_content AS contri_pct_to_cem_content, 
        LTrim(RTrim(Replace(iloc.max_slump, Chr(160), ' '))) AS max_slump, 
        LTrim(RTrim(Replace(iloc.min_slump, Chr(160), ' '))) AS min_slump, 
        LTrim(RTrim(Replace(iloc.slump, Chr(160), ' '))) AS slump, 
        LTrim(RTrim(Replace(iloc.modifier_slump, Chr(160), ' '))) AS modifier_slump, 
        LTrim(RTrim(Replace(iloc.slump_uom, Chr(160), ' '))) AS slump_uom, 
        iloc.air_pct AS air_pct, 
        iloc.lwt_qty AS lwt_qty, 
        iloc.modified_date AS modified_date, 
        iloc.order_dosage_qty AS order_dosage_qty, 
        LTrim(RTrim(Replace(iloc.item_status_code, Chr(160), ' '))) AS item_status_code, 
        iloc.batch_matl_flag AS batch_matl_flag, 
        iloc.solid_matl_spec_grav AS solid_matl_spec_grav, 
        iloc.admix_effectiveness AS admix_effectiveness, 
        iloc.loading_speed_pct AS loading_speed_pct, 
        iloc.curr_opt_cost AS curr_opt_cost, 
        iloc.prev_opt_cost AS prev_opt_cost, 
        iloc.opt_cost_effect_date AS opt_cost_effect_date, 
        LTrim(RTrim(Replace(iloc.mobileticket_code, Chr(160), ' '))) AS mobileticket_code, 
        LTrim(RTrim(Replace(iloc.inactive_code, Chr(160), ' '))) AS inactive_code, 
        iloc.inactive_date AS inactive_date, 
        iloc.over_mixing_time_allow AS over_mixing_time_allow, 
        LTrim(RTrim(Replace(iloc.order_num, Chr(160), ' '))) AS order_num, 
        LTrim(RTrim(Replace(iloc.external_plant_code, Chr(160), ' '))) AS external_plant_code, 
        iloc.update_date AS update_date 
From iloc iloc 
Order By    LTrim(RTrim(Replace(iloc.loc_code, Chr(160), ' '))),
            LTrim(RTrim(Replace(iloc.item_code, Chr(160), ' '))) 

Select  'ICST' As Table_Name,
        Row_number() Over (Order By LTrim(RTrim(Replace(icst.loc_code, Chr(160), ' '))), LTrim(RTrim(Replace(icst.item_code, Chr(160), ' '))), LTrim(RTrim(Replace(icst.const_item_code, Chr(160), ' ')))) As RowNumber,
        LTrim(RTrim(Replace(icst.item_code, Chr(160), ' '))) AS item_code, 
        LTrim(RTrim(Replace(icst.loc_code, Chr(160), ' '))) AS loc_code, 
        LTrim(RTrim(Replace(icst.const_item_code, Chr(160), ' '))) AS const_item_code, 
        icst.sort_line_num AS sort_line_num, 
        icst.qty AS qty, 
        LTrim(RTrim(Replace(icst.qty_uom, Chr(160), ' '))) AS qty_uom, 
        icst.vol_pct AS vol_pct, 
        icst.modified_date AS modified_date, 
        icst.dose_qty AS dose_qty, 
        icst.trim_adj AS trim_adj, 
        LTrim(RTrim(Replace(icst.trim_adj_uom, Chr(160), ' '))) AS trim_adj_uom, 
        icst.design_qty AS design_qty, 
        LTrim(RTrim(Replace(icst.design_qty_uom, Chr(160), ' '))) AS design_qty_uom, 
        icst.water_trim AS water_trim, 
        LTrim(RTrim(Replace(icst.water_trim_uom, Chr(160), ' '))) AS water_trim_uom, 
        icst.update_date AS update_date 
From icst icst 
Order By    LTrim(RTrim(Replace(icst.loc_code, Chr(160), ' '))), 
            LTrim(RTrim(Replace(icst.item_code, Chr(160), ' '))), 
            LTrim(RTrim(Replace(icst.const_item_code, Chr(160), ' ')))

Select  'IMLB' As Table_Name,
        Row_number() Over (Order By LTrim(RTrim(Replace(imlb.loc_code, Chr(160), ' '))), LTrim(RTrim(Replace(imlb.item_code, Chr(160), ' '))), LTrim(RTrim(Replace(imlb.batch_code, Chr(160), ' ')))) As RowNumber,
        LTrim(RTrim(Replace(imlb.item_code, Chr(160), ' '))) AS item_code, 
        LTrim(RTrim(Replace(imlb.loc_code, Chr(160), ' '))) AS loc_code, 
        LTrim(RTrim(Replace(imlb.batch_code, Chr(160), ' '))) AS batch_code, 
        imlb.sort_line_num AS sort_line_num, 
        LTrim(RTrim(Replace(imlb.descr, Chr(160), ' '))) AS descr, 
        LTrim(RTrim(Replace(imlb.short_descr, Chr(160), ' '))) AS short_descr, 
        imlb.modified_date AS modified_date, 
        LTrim(RTrim(Replace(imlb.external_plant_code, Chr(160), ' '))) AS external_plant_code, 
        imlb.update_date AS update_date 
From imlb imlb 
Order By    LTrim(RTrim(Replace(imlb.loc_code, Chr(160), ' '))),
            LTrim(RTrim(Replace(imlb.item_code, Chr(160), ' '))),
            LTrim(RTrim(Replace(imlb.batch_code, Chr(160), ' ')))
        
Select  'ICAT' As Table_Name,
        Row_number() Over (Order By LTrim(RTrim(Replace(icat.item_cat, Chr(160), ' ')))) As RowNumber,
        LTrim(RTrim(Replace(icat.item_cat, Chr(160), ' '))) AS item_cat, 
        LTrim(RTrim(Replace(icat.descr, Chr(160), ' '))) AS descr, 
        LTrim(RTrim(Replace(icat.short_descr, Chr(160), ' '))) AS short_descr, 
        LTrim(RTrim(Replace(icat.item_type, Chr(160), ' '))) AS item_type, 
        LTrim(RTrim(Replace(icat.matl_type, Chr(160), ' '))) AS matl_type, 
        LTrim(RTrim(Replace(icat.dflt_order_uom, Chr(160), ' '))) AS dflt_order_uom, 
        LTrim(RTrim(Replace(icat.dflt_price_uom, Chr(160), ' '))) AS dflt_price_uom, 
        LTrim(RTrim(Replace(icat.dflt_batch_uom, Chr(160), ' '))) AS dflt_batch_uom, 
        LTrim(RTrim(Replace(icat.dflt_invy_uom, Chr(160), ' '))) AS dflt_invy_uom, 
        LTrim(RTrim(Replace(icat.dflt_order_qty_ext_code, Chr(160), ' '))) AS dflt_order_qty_ext_code, 
        icat.dflt_order_dosage_qty AS dflt_order_dosage_qty, 
        LTrim(RTrim(Replace(icat.dflt_order_dosage_qty_uom, Chr(160), ' '))) AS dflt_order_dosage_qty_uom, 
        LTrim(RTrim(Replace(icat.dflt_price_qty_ext_code, Chr(160), ' '))) AS dflt_price_qty_ext_code, 
        LTrim(RTrim(Replace(icat.dflt_tkt_qty_ext_code, Chr(160), ' '))) AS dflt_tkt_qty_ext_code, 
        LTrim(RTrim(Replace(icat.dflt_delv_uom, Chr(160), ' '))) AS dflt_delv_uom, 
        icat.dflt_per_cem_wgt_divisor AS dflt_per_cem_wgt_divisor, 
        LTrim(RTrim(Replace(icat.dflt_purch_uom, Chr(160), ' '))) AS dflt_purch_uom, 
        icat.dflt_strgth AS dflt_strgth, 
        LTrim(RTrim(Replace(icat.dflt_strgth_uom, Chr(160), ' '))) AS dflt_strgth_uom, 
        LTrim(RTrim(Replace(icat.dflt_slump, Chr(160), ' '))) AS dflt_slump, 
        LTrim(RTrim(Replace(icat.dflt_slump_uom, Chr(160), ' '))) AS dflt_slump_uom, 
        LTrim(RTrim(Replace(icat.dflt_rpt_uom, Chr(160), ' '))) AS dflt_rpt_uom, 
        LTrim(RTrim(Replace(icat.dflt_cem_type, Chr(160), ' '))) AS dflt_cem_type, 
        LTrim(RTrim(Replace(icat.dflt_agg_size, Chr(160), ' '))) AS dflt_agg_size, 
        icat.dflt_min_temp AS dflt_min_temp, 
        icat.dflt_pct_recycle AS dflt_pct_recycle, 
        LTrim(RTrim(Replace(icat.dflt_proj_restrict, Chr(160), ' '))) AS dflt_proj_restrict, 
        icat.update_date AS update_date 
From icat icat 
Order By LTrim(RTrim(Replace(icat.item_cat, Chr(160), ' ')))

Select  'UOMS' As Table_Name,
        Row_number() Over (Order By LTrim(RTrim(Replace(uoms.uom, Chr(160), ' ')))) As RowNumber,
        LTrim(RTrim(Replace(uoms.uom, Chr(160), ' '))) AS uom, 
        LTrim(RTrim(Replace(uoms.descr, Chr(160), ' '))) AS descr, 
        LTrim(RTrim(Replace(uoms.short_descr, Chr(160), ' '))) AS short_descr, 
        LTrim(RTrim(Replace(uoms.abbr, Chr(160), ' '))) AS abbr, 
        uoms.uom_type AS uom_type, 
        uoms.predef_flag AS predef_flag, 
        uoms.accum_flag AS accum_flag, 
        uoms.imperial_flag AS imperial_flag, 
        LTrim(RTrim(Replace(uoms.system_conv_uom, Chr(160), ' '))) AS system_conv_uom, 
        uoms.update_date AS update_date 
From uoms uoms 
Order By LTrim(RTrim(Replace(uoms.uom, Chr(160), ' ')))
